### PR TITLE
Assorted tweaks.

### PR DESCRIPTION
**Pull request by XhmikosR**
@ostark: let me know about the php-cs-fixer config. I tried to follow your current style and just make it consistent. :)

### CODE REVIEW

**Comment by ostark** [comment]
Thanks, for adding the cs-fixer. I'm still undecided about yoda style :-)
Will have a look at phpstan

**Comment by XhmikosR** [comment]
Let me know if you want me to make any changes and I can just rebase. :) The style is your call, I just went with the consistent solution for yoda.

**Comment by XhmikosR** [comment]
I tried to fix the phpstan error by adding `%currentWorkingDirectory%/bin/craft-copy-installer.php` in its config but then it can't find the files referenced there like `autoload.php`. Perhaps I should remove the3 bin folder addition. I just added it because it correctly warned about the missing DotEnv dep (which worked all this time since most people already have it in their deps).

**Comment by XhmikosR** [comment]
@ostark: I cleaned this up a bit. I removed the bin addition to phpstan, but feel free to add it if you make it work. I also tweaked php-cs-fixer config to match your style more (no sorting of imports). And I added one last consistency patch which uses `ExitCode::OK` instead of 0.

**Comment by XhmikosR** [comment]
Nope, it loads it from vendor and works cross-platform.

**Comment by ostark** [comment]
Thanks for your efforts!

**Pull request merged**
